apps/staffs/urls.py
from django.urls import path

from .views import (
    StaffCreateView,
    StaffDeleteView,
    StaffDetailView,
    StaffListView,
    StaffUpdateView,
)

urlpatterns = [
    path("list/", StaffListView.as_view(), name="staff-list"),
    path("<int:pk>/", StaffDetailView.as_view(), name="staff-detail"),
    path("create/", StaffCreateView.as_view(), name="staff-create"),
    path("<int:pk>/update/", StaffUpdateView.as_view(), name="staff-update"),
    path("<int:pk>/delete/", StaffDeleteView.as_view(), name="staff-delete"),
]

csc_app/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from apps.students import views
handler404 = 'apps.students.views.handler404'
urlpatterns = [
    path('admin/', admin.site.urls , name='admin'),
    path("accounts/", include("django.contrib.auth.urls")),
    path("", include("apps.corecode.urls")),
    path("student/", include("apps.students.urls")),
    path("staff/", include("apps.staffs.urls")),
    path("finance/", include("apps.finance.urls")),
    path("result/", include("apps.result.urls")),
    path("enquiry/",include("apps.enquiry.urls")),
    path('public/student/<int:pk>/', views.PublicView.as_view(), name='public_student_profile'),
    path("revenue/", include("apps.revenue.urls")),
    path("course/", include("apps.course.urls")),
    path("batches/",include("apps.batch.urls"))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/staffs/models.py
from django.core.validators import RegexValidator
from django.db import models
from django.urls import reverse
from django.utils import timezone
from datetime import datetime



class Staff(models.Model):
    STATUS = [("active", "Active"), ("inactive", "Inactive")]
    staff_roll = [("Administrative staff","Administrative staff"),("Acadamic Staff","Acadamic Staff")]
    certificate_choice = [("Aadhar card","Aadhar card"),("Degree certificate","Degree certificate"),("Resume","Resume")]
    GENDER = [("male", "Male"), ("female", "Female")]
    RELIGION_CHOICE = [('Hindu','Hindu'),('Christian','Christian'),('Muslim','Muslim'),("others","others")]
    COMMUNITY_CHOICE = [('OC','OC'),('BC','BC'),('MBC','MBC'),('ST/SC','ST/SC'),("others","others")]
    current_status = models.CharField(max_length=10, choices=STATUS, default="active")
    staff_role = models.CharField("Staff Role",max_length=1024,blank=True,choices=staff_roll)
    name = models.CharField(max_length=200)
    gender = models.CharField(max_length=10, choices=GENDER, default="male")
    date_of_birth = models.DateField(default=timezone.now)
    date_of_admission = models.DateField("Date of Join",default=timezone.now)
    quali = models.CharField("Qualification",blank=True, max_length=500,null=True)
    study_year = models.IntegerField("If undergoing Year",blank=True,default=None,null=True)
    study_colleg = models.CharField("College Name",max_length=1024,blank=True)
    religion = models.CharField("Religion",max_length=554,default="Hindu",choices=RELIGION_CHOICE)
    community = models.CharField("Community",max_length=524,default="OC", choices=COMMUNITY_CHOICE)
    software_pro = models.CharField("Software Proficiency",max_length=255,blank=True)
    last_salary = models.CharField("Last Job Salary drawn",max_length=255,blank=True)
    working_exp = models.TextField("Working Experience",blank=True,null=True)
    mobile_num_regex = RegexValidator(
        regex="^[0-9]{10,15}$", message="Entered mobile number isn't in a right format!"
    )
    mobile_number = models.CharField(
        validators=[mobile_num_regex], max_length=13, blank=True
    )
    email = models.EmailField("Email", blank=False, default="")


    address = models.CharField("Address", max_length=255,default=None,blank=True)
    address1 = models.CharField("Address Line 2", max_length=255,default=None,blank=True,null=True)
    address2 = models.CharField("Address Line 3", max_length=255,default=None,blank=True,null=True)
    taluka = models.CharField("Taluk",max_length=255,null=True,default=None,blank=True)
    district = models.CharField("District",max_length=255,default="",blank=True)
    pincode = models.IntegerField("Pincode", blank=True, default=None)
    passport = models.ImageField("Photo",blank=True, upload_to="staff/certificates/")
    aadhar_card = models.ImageField("Aadhar Card",blank=True, upload_to="staff/certificates/")
    degree_certificate = models.ImageField("Degree Certificate",blank=True, upload_to="staff/certificates/")
    resume = models.ImageField("Resume",blank=True, upload_to="staff/certificates/")
    


    def __str__(self):
        return f"{self.name}"

    def get_absolute_url(self):
        return reverse("staff-detail", kwargs={"pk": self.pk})
    def age(self):
        today = datetime.now().date()
        birthdate = self.date_of_birth
        age = today.year - birthdate.year - ((today.month, today.day) < (birthdate.month, birthdate.day))
        return age
    

apps/staffs/forms.py
from django import forms
from .models import Staff

class StaffForm(forms.ModelForm):
    class Meta:
        model = Staff
        fields = '__all__'

    def clean_mobile_number(self):
        mobile_number = self.cleaned_data['mobile_number']
        return mobile_number

apps/staffs/views.py
from django.contrib.messages.views import SuccessMessageMixin
from django.forms import widgets
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import DetailView, ListView
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from django import forms
import os
from .models import Staff


class StaffListView(ListView):
    model = Staff


class StaffDetailView(DetailView):
    model = Staff
    template_name = "staffs/staff_detail.html"


class StaffCreateView(SuccessMessageMixin, CreateView):
    model = Staff
    fields = "__all__"
    success_message = "New staff successfully added"

    def get_form(self):
        """add date picker in forms"""
        form = super(StaffCreateView, self).get_form()
        form.fields["date_of_birth"].widget = widgets.DateInput(attrs={"type": "date"})
        form.fields["date_of_admission"].widget = widgets.DateInput(
            attrs={"type": "date"}
        )
        form.fields["address"].widget = widgets.Textarea(attrs={"rows": 1})
        form.fields["working_exp"].widget = widgets.Textarea(attrs={"rows": 1})
        return form
    def form_valid(self, form):
        # Handle file uploads here
        form.instance.passport = self.request.FILES.get('passport')
        form.instance.aadhar_card = self.request.FILES.get('aadhar_card')
        form.instance.degree_certificate = self.request.FILES.get('degree_certificate')
        form.instance.resume = self.request.FILES.get('resume')
        return super().form_valid(form)
    


class StaffUpdateView(SuccessMessageMixin, UpdateView):
    model = Staff
    fields = "__all__"
    success_message = "Record successfully updated."

    def get_form(self):
        """add date picker in forms"""
        form = super(StaffUpdateView, self).get_form()
        form.fields["date_of_birth"].widget = widgets.DateInput(attrs={"type": "date"})
        form.fields["date_of_admission"].widget = widgets.DateInput(
            attrs={"type": "date"}
        )
        form.fields["address"].widget = widgets.Textarea(attrs={"rows": 1})
        form.fields["working_exp"].widget = widgets.Textarea(attrs={"rows": 1})
        return form
    def form_valid(self, form):
        # Handle file uploads here
        form.instance.passport = self.request.FILES.get('passport')
        form.instance.aadhar_card = self.request.FILES.get('aadhar_card')
        form.instance.degree_certificate = self.request.FILES.get('degree_certificate')
        form.instance.resume = self.request.FILES.get('resume')
        return super().form_valid(form)
    def save(self, *args, **kwargs):
        # Delete previous images before saving new ones
        if self.pk:
            original = Staff.objects.get(pk=self.pk)
            if self.passport and original.passport != self.passport:
                if os.path.isfile(original.passport.path):
                    os.remove(original.passport.path)
            if self.aadhar_card and original.aadhar_card != self.aadhar_card:
                if os.path.isfile(original.aadhar_card.path):
                    os.remove(original.aadhar_card.path)
            if self.degree_certificate and original.degree_certificate != self.degree_certificate:
                if os.path.isfile(original.degree_certificate.path):
                    os.remove(original.degree_certificate.path)
            if self.resume and original.resume != self.resume:
                if os.path.isfile(original.resume.path):
                    os.remove(original.resume.path)
        super().save(*args, **kwargs)

class StaffDeleteView(DeleteView):
    model = Staff
    success_url = reverse_lazy("staff-list")

apps/staffs/templates/staffs/staff_confirm_delete.html
{% extends 'base.html' %}


{% block title %}
{% endblock title %}


{% block content %}

<form action="" method="POST">
  {% csrf_token %}

  <div class="alert">
    <p>Are you sure you want to delete "{{ object }}"?</p>
    <p>All contents attached to this staff will be deleted</p>
  </div>

  <input type="submit" class="btn btn-primary" value="Confirm">

</form>


{% endblock content %}

apps/staffs/templates/staffs/staff_detail.html
{% extends 'base.html' %}
{% load static %}


{% block content-header %}
<div class="card-header">
  <div class="card-tools">
    <a href="#" class="btn btn-tool">Print</a>
    <a href="{% url 'staff-update' object.id %}" class="btn btn-tool">
      <i class="fas fa-edit"></i>
    </a>
    <a href="{% url 'staff-delete' object.id %}" class="btn btn-tool">
      <i class="fas fa-times"></i>
    </a>
  </div>
</div>
{% endblock content-header %}

{% block content %}
<style>
  .section {
    padding: 20px 0;
    position: relative;
}
.gray-bg {
    background-color: #f5f5f5;
}
img {
    max-width: 70%;
}
img {
  border-radius : 20px;
  height:400px;
    vertical-align: middle;
    border-style: none;
}
/* About Me 
---------------------*/
.about-text h3 {
  font-size: 45px;
  font-weight: 700;
  margin: 0 0 6px;
}
@media (max-width: 767px) {
  .about-text h3 {
    font-size: 35px;
  }
}
.about-text h6 {
  font-weight: 600;
  margin-bottom: 15px;
}
@media (max-width: 767px) {
  .about-text h6 {
    font-size: 18px;
  }
}
.about-text p {
  font-size: 18px;
  max-width: 450px;
}
.about-text p mark {
  font-weight: 600;
  color: #20247b;
}

.about-list {
  padding-top: 10px;
}
.about-list .media {
  padding: 5px 0;
}
.about-list label {
  color: #20247b;
  font-weight: 600;
  width: 108px;
  margin: 0;
  position: relative;
}
.about-list label:after {
  content: "";
  position: absolute;
  top: 0;
  bottom: 0;
  right: 11px;
  width: 1px;
  height: 12px;
  background: #20247b;
  -moz-transform: rotate(15deg);
  -o-transform: rotate(15deg);
  -ms-transform: rotate(15deg);
  -webkit-transform: rotate(15deg);
  transform: rotate(15deg);
  margin: auto;
  opacity: 0.5;
}
.about-list p {
  margin: 0;
  font-size: 15px;
}

@media (max-width: 991px) {
  .about-avatar {
    margin-top: 30px;
  }
}

.about-section .counter {
  padding: 22px 20px;
  background: #ffffff;
  border-radius: 10px;
  box-shadow: 0 0 30px rgba(31, 45, 61, 0.125);
}
.about-section .counter .count-data {
  margin-top: 10px;
  margin-bottom: 10px;
}
.about-section .counter .count {
  font-weight: 700;
  color: #20247b;
  margin: 0 0 5px;
}
.about-section .counter p {
  font-weight: 600;
  margin: 0;
}
mark {
    background-image: linear-gradient(rgba(252, 83, 86, 0.6), rgba(252, 83, 86, 0.6));
    background-size: 100% 3px;
    background-repeat: no-repeat;
    background-position: 0 bottom;
    background-color: transparent;
    padding: 0;
    color: currentColor;
}
.theme-color {
    color: #fc5356;
}
.dark-color {
    color: #20247b;
}

</style>
<section class="section about-section gray-bg" id="about">
  <div class="container">
      <div class="row align-items-center flex-row-reverse">
          <div class="col-lg-7">
              <div class="about-text go-to">
                  <h3 class="dark-color">{{object.name}}</h3>
                  <h6 class="theme-color lead">Staff Role : {{object.staff_role}}</h6>
                  <p>{{object.software_pro}}</p>
                  <div class="row about-list">
                      <div class="col-md-6">
                          <div class="media">
                              <label>Birthday</label>
                              <p>{{object.date_of_birth}}</p>
                          </div>
                          <div class="media">
                              <label>Age</label>
                              <p>{{object.age}}</p>
                          </div>
                          <div class="media">
                              <label>Qualifications</label>
                              <p>{{object.quali}}</p>
                          </div>
                          <div class="media">
                              <label>Address</label>
                              <p>{{object.address}}</p>
                              <p>{{object.address1}}</p>
                              <p>{{object.taluka}}</p>
                              <p>{{object.district}} {{object.pincode}}</p>
                              

                              
                          </div>
                      </div>
                      <div class="col-md-6">
                          <div class="media">
                              <label>E-mail</label>
                              <p>{{object.email}}</p>
                          </div>
                          <div class="media">
                              <label>Phone</label>
                              <p>{{object.mobile_number}}</p>
                          </div>
                          <div class="media">
                              <label>From on</label>
                              <p>{{object.date_of_admission}}</p>
                          </div>
                          <div class="media">
                              <label>Id</label>
                              <p>{{object.id}}</p>
                          </div>
                      </div>
                  </div>
              </div>
          </div>
          <div class="col-lg-5">
              <div class="about-avatar">
                {% if object.passport %}
                <img
                  src="{{ object.passport.url }}"
                 >
              {% else %}
                <img
                  src="{% static 'dist/img/avatar.png' %}"
                 >
              {% endif %}
              </div>
          </div>
      </div>
      <div class="card">
        <div class="card-body mt-5">
          
          {% if object.aadhar_card %}
            <a href="{{ object.aadhar_card.url }}" class="btn btn-primary" download>
              Download Aadhar Card
            </a>
          {% endif %}
          
          {% if object.degree_certificate %}
            <a href="{{ object.degree_certificate.url }}" class="btn btn-primary" download>
              Download Degree Certificate
            </a>
          {% endif %}
          
          {% if object.resume %}
            <a href="{{ object.resume.url }}" class="btn btn-primary" download>
              Download Resume
            </a>
          {% endif %}
          
        </div>
      </div>
  </div>
</section>


{% endblock content %}

apps/staffs/templates/staffs/staff_form.html
{% extends 'base.html' %}


{% block title %}

  {% if object %}
    Update {{ object }}
  {% else %}
    Add new student
  {% endif %}

{% endblock title %}


{% block content %}

<form action="" method="POST" enctype="multipart/form-data">
  {% csrf_token %}

  {% include 'corecode/form_snippet.html' %}

  {% if object %}
    <input type="submit" class="btn btn-primary" value="Update Record">
  {% else %}
    <input type="submit" class="btn btn-primary" value="Add new Staff">
  {% endif %}
</form>


{% endblock content %}

apps/staffs/templates/staffs/staff_list.html
{% extends 'base.html' %}

{% block title %}staffs{% endblock title %}

{% block breadcrumb %}
<a class="btn btn-primary" href="{% url 'staff-create' %}"><i
    class="fas fa-plus"></i> New staff</a>
{% endblock breadcrumb %}

{% block content %}
<div class="table-responsive">
  <table id="stafftable" class="table table-bordered table-hover">
    <thead class="thead-light">
      <tr>
        <th>S/N</th>
        <th>Fullname</th>
        <th>Gender</th>
        <th>Qualification</th>
        <th>Mobile Phone Number</th>
        <th>Status</th>
      </tr>
    </thead>
    <tbody>

      {% for staff in object_list %}
        <tr class='clickable-row' data-href="{% url 'staff-detail' staff.id %}">
          <td>{{ forloop.counter}}</td>
          <td>{{ staff.name}}</td>
          <td>{{ staff.get_gender_display}}</td>
          <td>{{ staff.quali }}</td>
          <td>{{ staff.mobile_number}}</td>
          <td>{{ staff.get_current_status_display}}</td>
        </tr>
      {% endfor %}

    </tbody>
  </table>
</div>
{% endblock content %}


{% block morejs %}
<script>
   $('#stafftable').DataTable({
    select: false
    });
</script>

{% endblock morejs %}